### PR TITLE
change link/background colours

### PR DESCRIPTION
**Pull request by stevefaulkner**
A11Y WET BLANKET - current colour contrast unreadable for oldsters like
me

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@stevefaulkner can you take a screen shot of before an after by an chance?

**Comment by stevefaulkner** [comment]
@marcoscaceres 
after
before

**Comment by marcoscaceres** [comment]
Yeah, I agree. The darker colors are a big improvement - even for a youngster like me :dancer:

**Comment by marcoscaceres** [comment]
I'm going to merge this, as it doesn't seem like a very controversial change.

**Pull request merged**
