### PR TITLE
Document how to use `otherLinks` (closes #3)

### LINKED ISSUE #3: document how to use otherLinks
Someone created this awesome feature for adding links to the header of a document... but it's not documented. Someone should write docs for it.

### PR DESCRIPTION
**Pull request by marcoscaceres**
It's not really clear from the contribution guide which file I should actually be editing... so I kinda just guessed. I couldn't figure out how the master document is then stitched together. Would be nice to document the build process just a little bit.

### CODE REVIEW

**Comment by darobin** [comment]
That's a great start, thanks, but one (unspoken) rule is for everything that's in the refs to also be in the guide. Do you mind adding if only just a few words (even just "if you need more power than...") to src/guide.html please?

**Comment by marcoscaceres** [comment]
Ah, ok... I thought maybe the guide was being magically constructed from the refs.

**Comment by marcoscaceres** [comment]
ok, how's that?

**Comment by darobin** [comment]
Nah, the guide is written by hand, but the refs get magically constructed (and linked).

Thanks!

**Comment by marcoscaceres** [comment]
I knew there would be some magic somewhere :)

**Pull request merged**
